"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';
import { createClient } from '@/utils/supabase/client';

type Locale = 'ko' | 'en' | 'ja';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 번역 데이터 (간소화)
const messages = {
  ko: {
    "nav.news": "새소식/공지사항",
    "nav.characters": "캐릭터 공략",
    "nav.board": "버파라운지",
    "nav.login": "로그인",
    "nav.logout": "로그아웃",
    "common.greeting": "님",
    "hero.tag": "글로벌 K-pop 팬 커뮤니티",
    "hero.title": "K-pop을 사랑하는 모든 팬을 위한 공간",
    "hero.subtitle": "아티스트 소식, 팬 게시판, 다국어 자동번역으로 전 세계 K-pop 팬과 소통하세요.",
    "hero.desc": "K-pop 팬 커뮤니티에 오신 것을 환영합니다.",
    "hero.enter": "커뮤니티 입장",
    "hero.cta": "커뮤니티 입장",
    "board.title": "누구나 즐거운 ",
    "board.highlight": "버파 라운지",
    "board.desc": "\"사소한 질문도 괜찮아요!\" 버린이부터 전설의 고수까지, 함께 웃으며 소통하는 공간입니다.",
    "board.search": "게시글 검색...",
    "board.write": "글쓰기",
    "board.table.title": "제목",
    "board.table.author": "글쓴이",
    "board.table.likes": "추천",
    "board.table.views": "조회",
    "board.table.date": "날짜",
    "board.empty": "등록된 게시글이 없습니다. 첫 번째 주인공이 되어보세요!",
    "board.write.back": "목록으로 돌아가기",
    "board.write.new": "게시글 등록",
    "board.write.edit": "게시글 수정",
    "board.write.category": "카테고리",
    "board.write.rank": "단위",
    "board.write.rankNone": "선택 안 함",
    "board.write.placeholder": "게시글의 제목을 입력하세요",
    "board.write.content": "내용",
    "board.write.contentPlaceholder": "작성하신 내용은 해외 유저들을 위해 자동으로 영어, 일어로 번역되어 제공됩니다 \n정보, 공략, 잡담 무엇이든 환영합니다. \n 링크, 유투브 주소를 복사해 붙여넣으면 자동으로 삽입됩니다.",
    "board.write.cancel": "취소",
    "board.write.submit": "게시글 등록",
    "board.write.update": "수정 완료",
    "board.write.guide": "작성하신 글은 커뮤니티 가이드라인을 준수해야 하며, 타인에 대한 비방이나 부적절한 내용은 제재될 수 있습니다.",
    "board.write.combo_help": "숫자(1-9) 입력 시 즉시 화살표로 변환",
    "board.write.joystick_help": "방향키 메뉴에서 원하는 화살표 직접 삽입",
    "board.load_error": "오류가 발생했습니다. 다시 시도해주세요.",
    "board.detail.post_not_found": "게시글을 찾을 수 없습니다",
    "board.detail.back": "목록으로 돌아가기",
    "board.detail.author": "작성자",
    "board.detail.like": "추천하기",
    "board.detail.unlike": "좋아요 취소",
    "board.detail.edit": "수정",
    "board.detail.pin": "상단 고정",
    "board.detail.unpin": "고정 해제",
    "board.detail.delete": "삭제",
    "board.detail.admin_delete": "강제 삭제",
    "board.detail.delete_confirm": "정말로 이 게시글을 삭제하시겠습니까?",
    "board.detail.delete_success": "게시글이 삭제되었습니다.",
    "board.detail.pin_success": "게시글이 상단에 고정되었습니다.",
    "board.detail.unpin_success": "상단 고정이 해제되었습니다.",
    "board.detail.translated": "번역된 제목",
    "board.detail.translating": "AI가 번역 중입니다...",
    "board.detail.translating_hint": "번역이 실패할 경우 재시도 버튼을 눌러 주세요.",
    "board.detail.translation_failed": "번역에 실패했습니다.",
    "board.detail.retry_translation": "다시 시도",
    "board.detail.view_original": "원문 보기",
    "board.detail.view_translated": "번역 보기",
    "board.translate": "번역 보기",
    "cat.debate": "토론",
    "cat.guide": "공략",
    "cat.question": "질문",
    "cat.chat": "잡담",
    "cat.video": "영상",
    "char.cat.tips": "공략/팁",
    "char.cat.combo": "콤보",
    "char.cat.vs_guide": "대전 가이드",
    "char.cat.question": "질문",
    "char.cat.chat": "잡담",
    "board.cat.greeting": "입문/복귀/첫인사",
    "board.cat.chat": "잡담/일상",
    "board.cat.question": "초보질문/도와줘요",
    "board.cat.tips": "정보/꿀팁",
    "board.cat.gear": "장비/세팅",
    "board.cat.match": "대전신청/후기",
    "board.cat.discussion": "토론",
    "board.cat.info": "정보",
    "board.cat.review": "소감",
    "news.title": "새소식/",
    "news.highlight": "공지사항",
    "news.desc": "K-pop 최신 소식과 공지사항을 확인하세요",
    "news.empty": "등록된 새소식이 없습니다.",
    "news.search": "새소식 검색...",
    "news.cat.notice": "공지사항",
    "news.cat.update": "업데이트",
    "news.cat.event": "이벤트",
    "news.cat.official": "공식 소식",
    "news.cat.community": "커뮤니티",
    "nav.gallery": "미디어 갤러리",
    "gallery.title": "미디어",
    "gallery.highlight": "갤러리",
    "gallery.desc": "K-pop 관련 영상과 이미지를 공유하고 감상해보세요",
    "gallery.empty": "등록된 미디어가 없습니다. 첫 번째 미디어를 올려보세요!",
    "gallery.search": "미디어 검색...",
    "gallery.cat.match_tournament": "명승부/대회",
    "gallery.cat.today_match": "게임플레이",
    "gallery.cat.combo_guide": "콤보/퍼포먼스",
    "gallery.cat.legendary": "고인의 생전 개쩔었던 순간",
    "gallery.cat.free": "기타/자유",
    "gallery.cat.showcase": "자랑/인증",
    "Comments.title": "댓글",
    "Comments.reply": "답글",
    "Comments.edit": "수정",
    "Comments.delete": "삭제",
    "Comments.cancel": "취소",
    "Comments.save": "저장",
    "Comments.post": "댓글등록",
    "Comments.placeholder": "댓글을 입력하세요...",
    "Comments.replyPlaceholder": "님에게 답글 작성...",
    "Comments.loginRequired": "댓글을 작성하려면",
    "Comments.loginLink": "로그인",
    "Comments.loginRequiredSuffix": "이 필요합니다.",
    "Comments.firstComment": "첫 번째 댓글을 남겨보세요!",
    "Comments.loading": "댓글 로딩 중...",
    "Comments.translated": "AI 번역됨",
    "Comments.translating": "AI 번역 중...",
    "Comments.translating_hint": "번역본은 저장되어 다음 방문 시 빠르게 표시됩니다",
    "Comments.translation_failed": "번역에 실패했습니다.",
    "Comments.retry_translation": "다시 시도",
    "Comments.writeTitlePre": "댓글",
    "Comments.writeTitleAccent": "입력",
    "Comments.deleted": "삭제된 댓글입니다.",
    "Comments.replyTo": "{name}에게 단 답글",
    "profile.pageTitle": "마이 프로필",
    "profile.pageDesc": "프로필을 관리하고 커뮤니티에 자신을 소개하세요",
    "profile.loadError": "프로필을 불러올 수 없습니다.",
    "profile.summary.edit": "편집",
    "profile.summary.save": "저장",
    "profile.summary.cancel": "취소",
    "profile.summary.nickname": "닉네임",
    "profile.summary.nicknamePlaceholder": "닉네임 입력",
    "profile.summary.commentLabel": "한줄 코멘트 (최대 100자)",
    "profile.summary.languageSelect": "언어 선택",
    "profile.gameInfo.title": "게임 정보",
    "profile.gameInfo.hint": "공개를 원하지 않는 정보는 공란으로 두세요",
    "profile.gameInfo.mainCharacter": "주 캐릭터",
    "profile.gameInfo.rank": "단위",
    "profile.gameInfo.viewRankBadges": "단위 뱃지 보기",
    "profile.gameInfo.rankNone": "선택 안 함",
    "profile.gameInfo.selectNone": "선택 안함",
    "profile.gameInfo.noInfo": "아직 게임 정보를 등록하지 않았습니다.",
    "profile.gameInfo.optional": "(선택사항)",
    "profile.stats.title": "활동 통계",
    "profile.stats.posts": "게시글",
    "profile.stats.comments": "댓글",
    "profile.stats.likes": "좋아요",
    "profile.security.title": "보안 설정",
    "profile.security.currentPassword": "현재 비밀번호",
    "profile.security.newPassword": "새 비밀번호",
    "profile.security.confirmPassword": "새 비밀번호 확인",
    "profile.security.currentPlaceholder": "현재 비밀번호 입력",
    "profile.security.newPlaceholder": "새 비밀번호 입력 (최소 6자)",
    "profile.security.confirmPlaceholder": "새 비밀번호 다시 입력",
    "profile.security.changeButton": "비밀번호 변경",
    "profile.recentPosts": "최근 게시글",
    "profile.recentComments": "최근 댓글",
    "profile.deletedPost": "삭제된 게시글",
    "profile.withdrawal.title": "회원 탈퇴",
    "profile.withdrawal.desc": "탈퇴 시 모든 게시글, 댓글, 프로필 정보가 영구 삭제되며 복구할 수 없습니다.",
    "profile.withdrawal.button": "회원 탈퇴하기",
    "profile.withdrawal.confirm": "정말로 탈퇴하시겠습니까? 모든 데이터가 삭제되며 복구할 수 없습니다.",
    "profile.avatar.sizeError": "파일 크기는 2MB를 초과할 수 없습니다.",
    "profile.avatar.typeError": "지원하지 않는 파일 형식입니다. (jpg, png, gif, webp만 가능)",
    "profile.avatar.uploadSuccess": "아바타가 업로드되었습니다.",
    "profile.avatar.uploadFailed": "아바타 업로드에 실패했습니다.",
    "profile.avatar.uploadError": "아바타 업로드 중 오류가 발생했습니다.",
    "profile.password.enterBoth": "현재 비밀번호와 새 비밀번호를 입력해주세요.",
    "profile.password.mismatch": "새 비밀번호가 일치하지 않습니다.",
    "profile.password.tooShort": "새 비밀번호는 최소 6자 이상이어야 합니다.",
    "profile.password.changeSuccess": "비밀번호가 변경되었습니다.",
    "profile.password.changeFailed": "비밀번호 변경에 실패했습니다.",
    "profile.password.changeError": "비밀번호 변경 중 오류가 발생했습니다.",
    "profile.save.success": "프로필이 업데이트되었습니다.",
    "profile.save.failed": "프로필 업데이트에 실패했습니다.",
    "profile.save.error": "프로필 저장 중 오류가 발생했습니다.",
    "profile.withdrawal.processError": "탈퇴 처리 중 오류가 발생했습니다.",
    "profile.public.notConfigured": "이 사용자는 아직 프로필을 설정하지 않았습니다.",
    "common.back": "돌아가기",
    "common.error": "오류가 발생했습니다.",
    "widget.profile.title": "My Profile",
    "widget.profile.loginPrompt": "로그인하여 커뮤니티 활동을\n시작하세요.",
    "widget.profile.loginButton": "LOGIN / JOIN",
    "widget.profile.welcomeBack": "Welcome Back",
    "widget.profile.welcomeUser": "님 환영합니다",
    "widget.profile.myPosts": "My Posts",
    "widget.profile.comments": "Comments",
    "widget.profile.logout": "Log Out",
    "widget.profile.joinedAt": "가입",
    "widget.posts.title": "NEW POSTS",
    "widget.posts.more": "More",
    "widget.posts.empty": "게시글이 없습니다.",
    "widget.hotTopics.title": "HOT TOPICS",
    "widget.comments.title": "Recent Comments",
    "widget.bestVideo.title": "BEST MEDIA",
    "characters.titlePrefix": "캐릭터",
    "characters.titleHighlight": "가이드",
    "characters.subtitle": "버추어 파이터 캐릭터들의 기술표와 유저 공략을 확인해보세요.",
    "character.guide.profile": "Character Profile",
    "character.guide.commandList": "Command List",
    "character.guide.comingSoon": "준비중입니다",
    "character.guide.commandGuide": "COMMAND GUIDE",
    "character.guide.frameData": "Frame Data →",
    "character.guide.comboGuides": "Combo Guides",
    "character.guide.play": "Play →",
    "moveList.selectMove": "기술을 선택하여 상세 정보를 확인하세요.",
    "moveList.frameData": "상세 데이터 (Frame Data)",
    "moveList.howToRead": "기술표 보는 법",
    "moveList.tooltip.frameSection": "■ 프레임",
    "moveList.tooltip.down": "다운",
    "moveList.tooltip.shake": "흔들림",
    "moveList.tooltip.evadeSection": "■ 회피 방향",
    "moveList.tooltip.evadeFront": "상대 복부 쪽(반회전)",
    "moveList.tooltip.evadeBack": "상대 등 쪽(반회전)",
    "moveList.tooltip.evadeBoth": "둘 다 피함",
    "moveList.tooltip.evadeNone": "피할 수 없음",
    "moveList.label.hitLevel": "판정",
    "moveList.label.damage": "대미지",
    "moveList.label.startup": "발생",
    "moveList.label.active": "지속",
    "moveList.label.total": "전체",
    "moveList.label.guard": "가드",
    "moveList.label.hit": "히트",
    "moveList.label.counter": "카운터",
    "moveList.label.crouchHit": "앉아 히트",
    "moveList.label.crouchCounter": "앉아 카운터",
    "moveList.label.stun": "경직차(C)",
    "moveList.label.evadeDir": "회피 방향",
    "moveList.label.throwBreak": "술 깨기",
    "moveList.label.notes": "비고",
    "moveList.noData": "데이터가 없습니다.",
    "moveList.comingSoon": "이 캐릭터의 기술 데이터는 준비 중입니다.",
    "moveList.theaterWide": "넓게보기",
    "moveList.theaterDefault": "기본크기",
    "moveList.searchPlaceholder": "기술명 또는 커맨드 검색...",
    "moveList.defaultCategory": "기본 기술",
    "legal.privacy.title1": "개인정보",
    "legal.privacy.title2": "처리방침",
    "legal.terms.title1": "이용",
    "legal.terms.title2": "약관",
    "footer.copyright": "© 2026 Kpop Community. All Rights Reserved.",
    "admin.ban.confirmBan": "사용자를 차단하시겠습니까?",
    "admin.ban.confirmUnban": "차단을 해제하시겠습니까?",
    "admin.ban.bannedSuccess": "사용자가 차단되었습니다.",
    "admin.ban.unbannedSuccess": "차단이 해제되었습니다.",
    "admin.ban.failed": "처리에 실패했습니다.",
    "admin.ban.error": "처리 중 오류가 발생했습니다.",
    "admin.ban.unbanButton": "차단 해제",
    "admin.ban.banButton": "사용자 차단",
    "board.write.draftRestore": "이전에 작성 중이던 임시 저장 내용이 있습니다. 불러오시겠습니까?",
    "board.write.cancelConfirm": "작성 중인 내용이 있습니다. 정말 취소하시겠습니까?\n저장되지 않은 내용은 모두 사라집니다.",
    "Comments.postFailed": "댓글 작성에 실패했습니다.",
    "Comments.deleteFailed": "삭제에 실패했습니다.",
    "Comments.editFailed": "수정에 실패했습니다.",
    "Comments.deleteConfirm": "댓글을 삭제하시겠습니까?",
    "Comments.adminDelete": "관리자 삭제",
    "pagination.prev": "이전 페이지",
    "pagination.next": "다음 페이지",
    "board.search.reset": "검색 초기화",
    "board.search.searchButton": "검색",
    "editor.directionInsert": "방향키 삽입",
    "editor.imageSizeError": "파일 크기는 5MB를 초과할 수 없습니다.",
    "editor.imageTypeError": "지원하지 않는 파일 형식입니다. (jpg, png, gif, webp만 가능)",
    "editor.imageUploadFailed": "이미지 업로드에 실패했습니다.",
    "editor.youtubePrompt": "YouTube URL을 입력하세요",
    "editor.imageUpload": "이미지 업로드",
    "editor.youtubeInsert": "YouTube 영상 삽입",
    "editor.videoSizeError": "파일 크기는 20MB를 초과할 수 없습니다.",
    "editor.videoTypeError": "지원하지 않는 파일 형식입니다. (mp4, webm, ogg, mov만 가능)",
    "editor.videoUploadFailed": "동영상 업로드에 실패했습니다.",
    "editor.videoUpload": "동영상 업로드 (최대 20MB, mp4/webm/ogg/mov)",
    "editor.twitterPrompt": "Twitter/X 게시글 URL을 입력하세요",
    "editor.twitterInsert": "Twitter 게시글 삽입",
    "editor.comboModeTitle": "숫자(1-9) 입력 시 화살표로 즉시 변환",
    "editor.deleteMediaConfirm": "미디어를 삭제하시겠습니까?",
    "board.write.titleRequired": "제목을 입력하세요",
    "board.write.contentRequired": "내용을 입력하세요",
    "notification.title": "알림",
    "notification.empty": "새로운 알림이 없습니다",
    "notification.markAllRead": "전체 읽음",
    "notification.deleteAll": "전체 삭제",
    "notification.comment": "님이 내 글에 댓글을 남겼습니다",
    "notification.like": "님이 내 글을 좋아합니다",
    "notification.reply": "님이 내 댓글에 답글을 남겼습니다",
    "notification.timeAgo.justNow": "방금 전",
    "notification.timeAgo.minutesAgo": "분 전",
    "notification.timeAgo.hoursAgo": "시간 전",
    "notification.timeAgo.daysAgo": "일 전",
    "notification.welcome.title": "Kpop Community에 오신 걸 환영해요!",
    "notification.welcome.body": "다른 K-pop 팬들과 더 즐겁게 소통할 수 있도록 프로필을 꾸미고 여러분의 이야기를 들려주세요!"
  },
  en: {
    "nav.news": "News / Notice",
    "nav.characters": "Characters",
    "nav.board": "VF Lounge",
    "nav.gallery": "Media Gallery",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "common.greeting": "",
    "hero.tag": "Global K-pop Fan Community",
    "hero.title": "A Space for Every K-pop Fan",
    "hero.subtitle": "Connect with K-pop fans worldwide through artist news, fan boards, and multilingual AI translation.",
    "hero.desc": "Welcome to the K-pop fan community.",
    "hero.enter": "Enter Community",
    "hero.cta": "Enter Community",
    "board.title": "Everyone's Fun ",
    "board.highlight": "VF Lounge",
    "board.desc": "\"No question is too small!\" A place to connect and share a laugh, from beginners to legendary pros.",
    "board.search": "Search posts...",
    "board.write": "Write",
    "board.table.title": "Subject",
    "board.table.author": "Author",
    "board.table.likes": "Likes",
    "board.table.views": "Views",
    "board.table.date": "Date",
    "board.empty": "No posts found. Be the first to post!",
    "board.write.back": "Back to list",
    "board.write.new": "New Post",
    "board.write.edit": "Edit Post",
    "board.write.category": "Category",
    "board.write.rank": "Rank",
    "board.write.rankNone": "None",
    "board.write.placeholder": "Enter post title",
    "board.write.content": "Content",
    "board.write.contentPlaceholder": "Your content is automatically translated into Korean and Japanese for users worldwide. \nInfo, guides, chat—anything is welcome. \nPaste links or YouTube URLs and they'll be inserted automatically.",
    "board.write.cancel": "Cancel",
    "board.write.submit": "Post",
    "board.write.update": "Update",
    "board.write.guide": "Your post must follow community guidelines. Inappropriate content may be restricted.",
    "board.write.combo_help": "Type 1-9 to insert arrows instantly",
    "board.write.joystick_help": "Select arrows manually from menu",
    "board.load_error": "An error occurred. Please try again.",
    "board.detail.post_not_found": "Post Not Found",
    "board.detail.back": "Back to list",
    "board.detail.author": "AUTHOR",
    "board.detail.like": "Like",
    "board.detail.unlike": "Unlike",
    "board.detail.edit": "Edit",
    "board.detail.pin": "Pin",
    "board.detail.unpin": "Unpin",
    "board.detail.delete": "Delete",
    "board.detail.admin_delete": "Force Delete",
    "board.detail.delete_confirm": "Are you sure you want to delete this post?",
    "board.detail.delete_success": "Post deleted.",
    "board.detail.pin_success": "Post pinned to top.",
    "board.detail.unpin_success": "Post unpinned.",
    "board.detail.translated": "Translated title",
    "board.detail.translating": "AI is translating...",
    "board.detail.translating_hint": "If translation fails, please press the retry button.",
    "board.detail.translation_failed": "Translation failed.",
    "board.detail.retry_translation": "Retry",
    "board.detail.view_original": "View Original",
    "board.detail.view_translated": "View Translation",
    "board.translate": "View Translation",
    "cat.debate": "DEBATE",
    "cat.guide": "GUIDE",
    "cat.question": "Q&A",
    "cat.chat": "CHAT",
    "cat.video": "VIDEO",
    "char.cat.tips": "Tips/Guide",
    "char.cat.combo": "Combo",
    "char.cat.vs_guide": "VS Guide",
    "char.cat.question": "Q&A",
    "char.cat.chat": "Chat",
    "board.cat.greeting": "Intro",
    "board.cat.chat": "Chat/Daily",
    "board.cat.question": "Beginner Q&A",
    "board.cat.tips": "Info/Tips",
    "board.cat.gear": "Gear/Setup",
    "board.cat.match": "Match/Review",
    "board.cat.discussion": "Discussion",
    "board.cat.info": "Info",
    "board.cat.review": "Review",
    "news.title": "NEWS/",
    "news.highlight": "NOTICE",
    "news.desc": "Check out the latest K-pop news and announcements",
    "news.empty": "No news found.",
    "news.search": "Search news...",
    "news.cat.notice": "Notice",
    "news.cat.update": "Update",
    "news.cat.event": "Event",
    "news.cat.official": "Official",
    "news.cat.community": "Community",
    "gallery.title": "Media",
    "gallery.highlight": "Gallery",
    "gallery.desc": "Share and enjoy K-pop videos and images",
    "gallery.empty": "No media yet. Be the first to post!",
    "gallery.search": "Search media...",
    "gallery.cat.match_tournament": "Epic Matches/Tournament",
    "gallery.cat.today_match": "Gameplay",
    "gallery.cat.combo_guide": "Combo/Performance",
    "gallery.cat.legendary": "Legendary Moments",
    "gallery.cat.free": "Other/Free",
    "gallery.cat.showcase": "Showcase",
    "Comments.title": "Comments",
    "Comments.reply": "Reply",
    "Comments.edit": "Edit",
    "Comments.delete": "Delete",
    "Comments.cancel": "Cancel",
    "Comments.save": "Save",
    "Comments.post": "Post Comment",
    "Comments.placeholder": "Write a comment...",
    "Comments.replyPlaceholder": "Reply to",
    "Comments.loginRequired": "Please",
    "Comments.loginLink": "login",
    "Comments.loginRequiredSuffix": "to write a comment.",
    "Comments.firstComment": "Be the first to comment!",
    "Comments.loading": "Loading comments...",
    "Comments.translated": "AI Translated",
    "Comments.translating": "Translating with AI...",
    "Comments.translating_hint": "Translations are saved for faster display on next visit",
    "Comments.translation_failed": "Translation failed.",
    "Comments.retry_translation": "Retry",
    "Comments.writeTitlePre": "Leave a",
    "Comments.writeTitleAccent": "Comment",
    "Comments.deleted": "This comment has been deleted.",
    "Comments.replyTo": "{name} · reply",
    "profile.pageTitle": "MY PROFILE",
    "profile.pageDesc": "Manage your profile and introduce yourself to the community",
    "profile.loadError": "Could not load profile.",
    "profile.summary.edit": "Edit",
    "profile.summary.save": "Save",
    "profile.summary.cancel": "Cancel",
    "profile.summary.nickname": "Nickname",
    "profile.summary.nicknamePlaceholder": "Enter nickname",
    "profile.summary.commentLabel": "One-line comment (max 100 chars)",
    "profile.summary.languageSelect": "Language",
    "profile.gameInfo.title": "Game Info",
    "profile.gameInfo.hint": "Leave blank if you don't want to share",
    "profile.gameInfo.mainCharacter": "Main character",
    "profile.gameInfo.rank": "Rank",
    "profile.gameInfo.viewRankBadges": "View rank badges",
    "profile.gameInfo.rankNone": "None",
    "profile.gameInfo.selectNone": "None",
    "profile.gameInfo.noInfo": "No game info registered yet.",
    "profile.gameInfo.optional": "(Optional)",
    "profile.stats.title": "Activity",
    "profile.stats.posts": "Posts",
    "profile.stats.comments": "Comments",
    "profile.stats.likes": "Likes",
    "profile.security.title": "Security",
    "profile.security.currentPassword": "Current password",
    "profile.security.newPassword": "New password",
    "profile.security.confirmPassword": "Confirm new password",
    "profile.security.currentPlaceholder": "Enter current password",
    "profile.security.newPlaceholder": "New password (min 6 chars)",
    "profile.security.confirmPlaceholder": "Confirm new password",
    "profile.security.changeButton": "Change password",
    "profile.recentPosts": "Recent posts",
    "profile.recentComments": "Recent comments",
    "profile.deletedPost": "Deleted post",
    "profile.withdrawal.title": "Delete Account",
    "profile.withdrawal.desc": "All posts, comments, and profile data will be permanently deleted and cannot be recovered.",
    "profile.withdrawal.button": "Delete Account",
    "profile.withdrawal.confirm": "Are you sure? All your data will be permanently deleted and cannot be recovered.",
    "profile.avatar.sizeError": "File size cannot exceed 2MB.",
    "profile.avatar.typeError": "Unsupported file format. (jpg, png, gif, webp only)",
    "profile.avatar.uploadSuccess": "Avatar uploaded successfully.",
    "profile.avatar.uploadFailed": "Failed to upload avatar.",
    "profile.avatar.uploadError": "An error occurred while uploading avatar.",
    "profile.password.enterBoth": "Please enter both current and new password.",
    "profile.password.mismatch": "New passwords do not match.",
    "profile.password.tooShort": "New password must be at least 6 characters.",
    "profile.password.changeSuccess": "Password changed successfully.",
    "profile.password.changeFailed": "Failed to change password.",
    "profile.password.changeError": "An error occurred while changing password.",
    "profile.save.success": "Profile updated successfully.",
    "profile.save.failed": "Failed to update profile.",
    "profile.save.error": "An error occurred while saving profile.",
    "profile.withdrawal.processError": "An error occurred during account deletion.",
    "profile.public.notConfigured": "This user has not set up their profile yet.",
    "common.back": "Go back",
    "common.error": "An error occurred.",
    "widget.profile.title": "My Profile",
    "widget.profile.loginPrompt": "Log in to start your\ncommunity experience.",
    "widget.profile.loginButton": "LOGIN / JOIN",
    "widget.profile.welcomeBack": "Welcome Back",
    "widget.profile.welcomeUser": "",
    "widget.profile.myPosts": "My Posts",
    "widget.profile.comments": "Comments",
    "widget.profile.logout": "Log Out",
    "widget.profile.joinedAt": "Joined",
    "widget.posts.title": "NEW POSTS",
    "widget.posts.more": "More",
    "widget.posts.empty": "No posts found.",
    "widget.hotTopics.title": "HOT TOPICS",
    "widget.comments.title": "Recent Comments",
    "widget.bestVideo.title": "BEST MEDIA",
    "characters.titlePrefix": "Character",
    "characters.titleHighlight": "Guide",
    "characters.subtitle": "Explore move lists and community guides for Virtua Fighter characters.",
    "character.guide.profile": "Character Profile",
    "character.guide.commandList": "Command List",
    "character.guide.comingSoon": "Coming soon",
    "character.guide.commandGuide": "COMMAND GUIDE",
    "character.guide.frameData": "Frame Data →",
    "character.guide.comboGuides": "Combo Guides",
    "character.guide.play": "Play →",
    "moveList.selectMove": "Select a move to view details.",
    "moveList.frameData": "Frame Data",
    "moveList.howToRead": "How to read",
    "moveList.tooltip.frameSection": "■ Frame",
    "moveList.tooltip.down": "Down",
    "moveList.tooltip.shake": "Shake",
    "moveList.tooltip.evadeSection": "■ Evade Direction",
    "moveList.tooltip.evadeFront": "Toward opponent's front (half turn)",
    "moveList.tooltip.evadeBack": "Toward opponent's back (half turn)",
    "moveList.tooltip.evadeBoth": "Evades both",
    "moveList.tooltip.evadeNone": "Cannot evade",
    "moveList.label.hitLevel": "Hit Level",
    "moveList.label.damage": "Damage",
    "moveList.label.startup": "Startup",
    "moveList.label.active": "Active",
    "moveList.label.total": "Total",
    "moveList.label.guard": "Guard",
    "moveList.label.hit": "Hit",
    "moveList.label.counter": "Counter",
    "moveList.label.crouchHit": "Crouch Hit",
    "moveList.label.crouchCounter": "Crouch Counter",
    "moveList.label.stun": "Stun (C)",
    "moveList.label.evadeDir": "Evade Dir",
    "moveList.label.throwBreak": "Throw Break",
    "moveList.label.notes": "Notes",
    "moveList.noData": "No data available.",
    "moveList.comingSoon": "Move data for this character is coming soon.",
    "moveList.theaterWide": "Wide",
    "moveList.theaterDefault": "Default",
    "moveList.searchPlaceholder": "Search moves name or command...",
    "moveList.defaultCategory": "Basic Moves",
    "legal.privacy.title1": "Privacy",
    "legal.privacy.title2": "Policy",
    "legal.terms.title1": "Terms of",
    "legal.terms.title2": "Service",
    "footer.copyright": "© 2026 Kpop Community. All Rights Reserved.",
    "admin.ban.confirmBan": "Are you sure you want to ban this user?",
    "admin.ban.confirmUnban": "Are you sure you want to unban this user?",
    "admin.ban.bannedSuccess": "User has been banned.",
    "admin.ban.unbannedSuccess": "User has been unbanned.",
    "admin.ban.failed": "Action failed.",
    "admin.ban.error": "An error occurred.",
    "admin.ban.unbanButton": "Unban",
    "admin.ban.banButton": "Ban User",
    "board.write.draftRestore": "You have a previously saved draft. Would you like to restore it?",
    "board.write.cancelConfirm": "You have unsaved content. Are you sure you want to cancel?\nAll unsaved content will be lost.",
    "Comments.postFailed": "Failed to post comment.",
    "Comments.deleteFailed": "Failed to delete.",
    "Comments.editFailed": "Failed to edit.",
    "Comments.deleteConfirm": "Are you sure you want to delete this comment?",
    "Comments.adminDelete": "Admin Delete",
    "pagination.prev": "Previous page",
    "pagination.next": "Next page",
    "board.search.reset": "Clear search",
    "board.search.searchButton": "Search",
    "editor.directionInsert": "Insert direction",
    "editor.imageSizeError": "File size cannot exceed 5MB.",
    "editor.imageTypeError": "Unsupported file format. (jpg, png, gif, webp only)",
    "editor.imageUploadFailed": "Failed to upload image.",
    "editor.youtubePrompt": "Enter YouTube URL",
    "editor.imageUpload": "Upload image",
    "editor.youtubeInsert": "Insert YouTube video",
    "editor.videoSizeError": "File size cannot exceed 20MB.",
    "editor.videoTypeError": "Unsupported file format. (mp4, webm, ogg, mov only)",
    "editor.videoUploadFailed": "Video upload failed.",
    "editor.videoUpload": "Upload Video (max 20MB, mp4/webm/ogg/mov)",
    "editor.twitterPrompt": "Enter Twitter/X post URL",
    "editor.twitterInsert": "Insert Twitter Post",
    "editor.comboModeTitle": "Convert numbers (1-9) to arrows instantly",
    "editor.deleteMediaConfirm": "Are you sure you want to delete this media?",
    "board.write.titleRequired": "Please enter a title.",
    "board.write.contentRequired": "Please enter content.",
    "notification.title": "Notifications",
    "notification.empty": "No new notifications",
    "notification.markAllRead": "Mark all read",
    "notification.deleteAll": "Delete all",
    "notification.comment": "commented on your post",
    "notification.like": "liked your post",
    "notification.reply": "replied to your comment",
    "notification.timeAgo.justNow": "Just now",
    "notification.timeAgo.minutesAgo": "m ago",
    "notification.timeAgo.hoursAgo": "h ago",
    "notification.timeAgo.daysAgo": "d ago",
    "notification.welcome.title": "Welcome to Kpop Community!",
    "notification.welcome.body": "Set up your profile to get started — add your nickname, favorite artist, and a short intro"
  },
  ja: {
    "nav.news": "ニュース/お知らせ",
    "nav.characters": "キャラクター攻略",
    "nav.board": "バパラウンジ",
    "nav.gallery": "メディアギャラリー",
    "nav.login": "ログイン",
    "nav.logout": "ログアウト",
    "common.greeting": "さん",
    "hero.tag": "グローバルK-popファンコミュニティ",
    "hero.title": "すべてのK-popファンのための空間",
    "hero.subtitle": "アーティスト情報、ファン掲示板、多言語AI翻訳で世界中のK-popファンとつながろう。",
    "hero.desc": "K-popファンコミュニティへようこそ。",
    "hero.enter": "コミュニティに入る",
    "hero.cta": "コミュニティに入る",
    "board.title": "みんなで楽しむ",
    "board.highlight": "バパラウンジ",
    "board.desc": "「小さな質問も大歓迎！」ビギナーから伝説の強者まで、笑いながら交流する場所です。",
    "board.search": "投稿を検索...",
    "board.write": "書き込み",
    "board.table.title": "タイトル",
    "board.table.author": "投稿者",
    "board.table.likes": "オススメ",
    "board.table.views": "閲覧",
    "board.table.date": "日付",
    "board.empty": "投稿がありません。最初の投稿者になりましょう！",
    "board.write.back": "リストに戻る",
    "board.write.new": "新規投稿",
    "board.write.edit": "投稿の編集",
    "board.write.category": "カテゴリ",
    "board.write.rank": "段位",
    "board.write.rankNone": "選択しない",
    "board.write.placeholder": "タイトルの入力",
    "board.write.content": "内容",
    "board.write.contentPlaceholder": "投稿内容は海外ユーザーのため、韓国語・英語に自動翻訳されて提供されます。 \n情報、攻略、雑談なんでも歓迎です。 \nリンクやYouTubeのURLを貼り付けると自動で挿入されます。",
    "board.write.cancel": "キャンセル",
    "board.write.submit": "投稿する",
    "board.write.update": "更新する",
    "board.write.guide": "コミュニティガイドラインを遵守してください。不適切な内容は削除される場合があります。",
    "board.write.combo_help": "1-9を入力すると即座に矢印に変換されます",
    "board.write.joystick_help": "メニューから矢印を選択して挿入",
    "board.load_error": "エラーが発生しました。もう一度お試しください。",
    "board.detail.post_not_found": "投稿が見つかりません",
    "board.detail.back": "リストに戻る",
    "board.detail.author": "投稿者",
    "board.detail.like": "オススメ",
    "board.detail.unlike": "キャンセル",
    "board.detail.edit": "編集",
    "board.detail.pin": "固定",
    "board.detail.unpin": "固定解除",
    "board.detail.delete": "削除",
    "board.detail.admin_delete": "強制削除",
    "board.detail.delete_confirm": "本当にこの投稿を削除しますか？",
    "board.detail.delete_success": "投稿を削除しました。",
    "board.detail.pin_success": "投稿をトップに固定しました。",
    "board.detail.unpin_success": "トップ固定を解除しました。",
    "board.detail.translated": "翻訳されたタイトル",
    "board.detail.translating": "AIが翻訳中です...",
    "board.detail.translating_hint": "翻訳に失敗した場合は、再試行ボタンを押してください。",
    "board.detail.translation_failed": "翻訳に失敗しました。",
    "board.detail.retry_translation": "再試行",
    "board.detail.view_original": "原文を見る",
    "board.detail.view_translated": "翻訳を見る",
    "board.translate": "翻訳を見る",
    "cat.debate": "討論",
    "cat.guide": "攻略",
    "cat.question": "質問",
    "cat.chat": "雑談",
    "cat.video": "動画",
    "char.cat.tips": "攻略/ヒント",
    "char.cat.combo": "コンボ",
    "char.cat.vs_guide": "対戦ガイド",
    "char.cat.question": "質問",
    "char.cat.chat": "雑談",
    "board.cat.greeting": "入門/復帰/初挨拶",
    "board.cat.chat": "雑談/日常",
    "board.cat.question": "初心者質問/助けて",
    "board.cat.tips": "情報/豆知識",
    "board.cat.gear": "機材/セッティング",
    "board.cat.match": "対戦募集/レビュー",
    "board.cat.discussion": "討論",
    "board.cat.info": "情報",
    "board.cat.review": "感想",
    "news.title": "ニュース/",
    "news.highlight": "お知らせ",
    "news.desc": "K-popの最新ニュースとお知らせを確認しましょう",
    "news.empty": "ニュースがありません。",
    "news.search": "ニュースを検索...",
    "news.cat.notice": "お知らせ",
    "news.cat.update": "アップデート",
    "news.cat.event": "イベント",
    "news.cat.official": "公式情報",
    "news.cat.community": "コミュニティ",
    "gallery.title": "メディア",
    "gallery.highlight": "ギャラリー",
    "gallery.desc": "K-pop関連の動画と画像を共有・鑑賞しましょう",
    "gallery.empty": "メディアがありません。最初のメディアを投稿しましょう！",
    "gallery.search": "メディアを検索...",
    "gallery.cat.match_tournament": "名勝負/大会",
    "gallery.cat.today_match": "ゲームプレイ",
    "gallery.cat.combo_guide": "コンボ/パフォーマンス",
    "gallery.cat.legendary": "伝説の瞬間",
    "gallery.cat.free": "その他/フリー",
    "gallery.cat.showcase": "自慢/認証",
    "Comments.title": "コメント",
    "Comments.reply": "返信",
    "Comments.edit": "編集",
    "Comments.delete": "削除",
    "Comments.cancel": "キャンセル",
    "Comments.save": "保存",
    "Comments.post": "コメントを投稿",
    "Comments.placeholder": "コメントを入力してください...",
    "Comments.replyPlaceholder": "さんへ返信...",
    "Comments.loginRequired": "コメントを書くには",
    "Comments.loginLink": "ログイン",
    "Comments.loginRequiredSuffix": "が必要です。",
    "Comments.firstComment": "最初のコメントを残してみましょう！",
    "Comments.loading": "コメントを読み込み中...",
    "Comments.translated": "AI翻訳済み",
    "Comments.translating": "AI翻訳中...",
    "Comments.translating_hint": "翻訳は保存され、次回の訪問時に素早く表示されます",
    "Comments.translation_failed": "翻訳に失敗しました。",
    "Comments.retry_translation": "再試行",
    "Comments.writeTitlePre": "コメントを",
    "Comments.writeTitleAccent": "書く",
    "Comments.deleted": "削除されたコメントです。",
    "Comments.replyTo": "{name}さんへの返信",
    "profile.pageTitle": "マイプロフィール",
    "profile.pageDesc": "プロフィールを管理してコミュニティに自己紹介しましょう",
    "profile.loadError": "プロフィールを読み込めませんでした。",
    "profile.summary.edit": "編集",
    "profile.summary.save": "保存",
    "profile.summary.cancel": "キャンセル",
    "profile.summary.nickname": "ニックネーム",
    "profile.summary.nicknamePlaceholder": "ニックネームを入力",
    "profile.summary.commentLabel": "一言コメント（100文字まで）",
    "profile.summary.languageSelect": "言語選択",
    "profile.gameInfo.title": "ゲーム情報",
    "profile.gameInfo.hint": "公開したくない場合は空欄にしてください",
    "profile.gameInfo.mainCharacter": "メインキャラ",
    "profile.gameInfo.rank": "段位",
    "profile.gameInfo.viewRankBadges": "段位バッジを見る",
    "profile.gameInfo.rankNone": "選択しない",
    "profile.gameInfo.selectNone": "選択しない",
    "profile.gameInfo.noInfo": "まだゲーム情報を登録していません。",
    "profile.gameInfo.optional": "（任意）",
    "profile.stats.title": "活動統計",
    "profile.stats.posts": "投稿",
    "profile.stats.comments": "コメント",
    "profile.stats.likes": "いいね",
    "profile.security.title": "セキュリティ",
    "profile.security.currentPassword": "現在のパスワード",
    "profile.security.newPassword": "新しいパスワード",
    "profile.security.confirmPassword": "新パスワード確認",
    "profile.security.currentPlaceholder": "現在のパスワードを入力",
    "profile.security.newPlaceholder": "新しいパスワード（6文字以上）",
    "profile.security.confirmPlaceholder": "新パスワードを再入力",
    "profile.security.changeButton": "パスワードを変更",
    "profile.recentPosts": "最近の投稿",
    "profile.recentComments": "最近のコメント",
    "profile.deletedPost": "削除された投稿",
    "profile.withdrawal.title": "退会",
    "profile.withdrawal.desc": "退会すると全ての投稿、コメント、プロフィール情報が完全に削除され、復元できません。",
    "profile.withdrawal.button": "退会する",
    "profile.withdrawal.confirm": "本当に退会しますか？全てのデータが削除され、復元できません。",
    "profile.avatar.sizeError": "ファイルサイズは2MBを超えることはできません。",
    "profile.avatar.typeError": "サポートされていないファイル形式です。(jpg, png, gif, webpのみ)",
    "profile.avatar.uploadSuccess": "アバターがアップロードされました。",
    "profile.avatar.uploadFailed": "アバターのアップロードに失敗しました。",
    "profile.avatar.uploadError": "アバターのアップロード中にエラーが発生しました。",
    "profile.password.enterBoth": "現在のパスワードと新しいパスワードを入力してください。",
    "profile.password.mismatch": "新しいパスワードが一致しません。",
    "profile.password.tooShort": "新しいパスワードは6文字以上である必要があります。",
    "profile.password.changeSuccess": "パスワードが変更されました。",
    "profile.password.changeFailed": "パスワードの変更に失敗しました。",
    "profile.password.changeError": "パスワード変更中にエラーが発生しました。",
    "profile.save.success": "プロフィールが更新されました。",
    "profile.save.failed": "プロフィールの更新に失敗しました。",
    "profile.save.error": "プロフィールの保存中にエラーが発生しました。",
    "profile.withdrawal.processError": "退会処理中にエラーが発生しました。",
    "profile.public.notConfigured": "このユーザーはまだプロフィールを設定していません。",
    "common.back": "戻る",
    "common.error": "エラーが発生しました。",
    "widget.profile.title": "マイプロフィール",
    "widget.profile.loginPrompt": "ログインしてコミュニティ活動を\n始めましょう。",
    "widget.profile.loginButton": "ログイン / 登録",
    "widget.profile.welcomeBack": "おかえりなさい",
    "widget.profile.welcomeUser": "さん、ようこそ",
    "widget.profile.myPosts": "投稿",
    "widget.profile.comments": "コメント",
    "widget.profile.logout": "ログアウト",
    "widget.profile.joinedAt": "登録",
    "widget.posts.title": "新着投稿",
    "widget.posts.more": "もっと見る",
    "widget.posts.empty": "投稿がありません。",
    "widget.hotTopics.title": "人気トピック",
    "widget.comments.title": "最近のコメント",
    "widget.bestVideo.title": "BEST MEDIA",
    "characters.titlePrefix": "キャラクター",
    "characters.titleHighlight": "ガイド",
    "characters.subtitle": "バーチャファイターキャラクターの技表とユーザー攻略をチェックしてみましょう。",
    "character.guide.profile": "キャラクタープロフィール",
    "character.guide.commandList": "コマンドリスト",
    "character.guide.comingSoon": "準備中です",
    "character.guide.commandGuide": "コマンドガイド",
    "character.guide.frameData": "フレームデータ →",
    "character.guide.comboGuides": "コンボガイド",
    "character.guide.play": "再生 →",
    "moveList.selectMove": "技を選択して詳細を確認してください。",
    "moveList.frameData": "詳細データ (Frame Data)",
    "moveList.howToRead": "技表の見方",
    "moveList.tooltip.frameSection": "■ フレーム",
    "moveList.tooltip.down": "ダウン",
    "moveList.tooltip.shake": "ゆれ",
    "moveList.tooltip.evadeSection": "■ 避け方向",
    "moveList.tooltip.evadeFront": "相手腹部側（半回転）",
    "moveList.tooltip.evadeBack": "相手背中側（半回転）",
    "moveList.tooltip.evadeBoth": "両方避ける",
    "moveList.tooltip.evadeNone": "避けられない",
    "moveList.label.hitLevel": "判定",
    "moveList.label.damage": "ダメージ",
    "moveList.label.startup": "発生",
    "moveList.label.active": "持続",
    "moveList.label.total": "全体",
    "moveList.label.guard": "ガード",
    "moveList.label.hit": "ヒット",
    "moveList.label.counter": "カウンター",
    "moveList.label.crouchHit": "しゃがみヒット",
    "moveList.label.crouchCounter": "しゃがみカウンター",
    "moveList.label.stun": "硬直差(C)",
    "moveList.label.evadeDir": "避け方向",
    "moveList.label.throwBreak": "投げ抜け",
    "moveList.label.notes": "備考",
    "moveList.noData": "データがありません。",
    "moveList.comingSoon": "このキャラクターの技データは準備中です。",
    "moveList.theaterWide": "ワイド",
    "moveList.theaterDefault": "標準",
    "moveList.searchPlaceholder": "技名またはコマンドを検索...",
    "moveList.defaultCategory": "基本技",
    "legal.privacy.title1": "個人情報",
    "legal.privacy.title2": "保護方針",
    "legal.terms.title1": "利用",
    "legal.terms.title2": "規約",
    "footer.copyright": "© 2026 Kpop Community. All Rights Reserved.",
    "admin.ban.confirmBan": "このユーザーをブロックしますか？",
    "admin.ban.confirmUnban": "ブロックを解除しますか？",
    "admin.ban.bannedSuccess": "ユーザーがブロックされました。",
    "admin.ban.unbannedSuccess": "ブロックが解除されました。",
    "admin.ban.failed": "処理に失敗しました。",
    "admin.ban.error": "処理中にエラーが発生しました。",
    "admin.ban.unbanButton": "ブロック解除",
    "admin.ban.banButton": "ユーザーをブロック",
    "board.write.draftRestore": "以前に作成していた下書きがあります。復元しますか？",
    "board.write.cancelConfirm": "作成中の内容があります。本当にキャンセルしますか？\n保存されていない内容は全て失われます。",
    "Comments.postFailed": "コメントの投稿に失敗しました。",
    "Comments.deleteFailed": "削除に失敗しました。",
    "Comments.editFailed": "編集に失敗しました。",
    "Comments.deleteConfirm": "コメントを削除しますか？",
    "Comments.adminDelete": "管理者削除",
    "pagination.prev": "前のページ",
    "pagination.next": "次のページ",
    "board.search.reset": "検索をクリア",
    "board.search.searchButton": "検索",
    "editor.directionInsert": "方向キーを挿入",
    "editor.imageSizeError": "ファイルサイズは5MBを超えることはできません。",
    "editor.imageTypeError": "サポートされていないファイル形式です。(jpg, png, gif, webpのみ)",
    "editor.imageUploadFailed": "画像のアップロードに失敗しました。",
    "editor.youtubePrompt": "YouTube URLを入力してください",
    "editor.imageUpload": "画像をアップロード",
    "editor.youtubeInsert": "YouTube動画を挿入",
    "editor.videoSizeError": "ファイルサイズは20MBを超えることができません。",
    "editor.videoTypeError": "サポートされていないファイル形式です。（mp4、webm、ogg、movのみ可能）",
    "editor.videoUploadFailed": "動画のアップロードに失敗しました。",
    "editor.videoUpload": "動画アップロード（最大20MB、mp4/webm/ogg/mov）",
    "editor.twitterPrompt": "Twitter/X投稿URLを入力してください",
    "editor.twitterInsert": "Twitter投稿を挿入",
    "editor.comboModeTitle": "数字(1-9)を入力すると即座に矢印に変換",
    "editor.deleteMediaConfirm": "このメディアを削除しますか？",
    "board.write.titleRequired": "タイトルを入力してください。",
    "board.write.contentRequired": "内容を入力してください。",
    "notification.title": "通知",
    "notification.empty": "新しい通知はありません",
    "notification.markAllRead": "全て既読",
    "notification.deleteAll": "全て削除",
    "notification.comment": "さんが投稿にコメントしました",
    "notification.like": "さんが投稿にいいねしました",
    "notification.reply": "さんがコメントに返信しました",
    "notification.timeAgo.justNow": "たった今",
    "notification.timeAgo.minutesAgo": "分前",
    "notification.timeAgo.hoursAgo": "時間前",
    "notification.timeAgo.daysAgo": "日前",
    "notification.welcome.title": "Kpop Communityへようこそ！",
    "notification.welcome.body": "プロフィールを設定してコミュニティを楽しみましょう。ニックネーム、好きなアーティスト、一言紹介を登録してみてください"
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>('en');

  useEffect(() => {
    const saved = localStorage.getItem('vf6-locale') as Locale | null;
    if (saved && ['ko', 'en', 'ja'].includes(saved)) {
      setLocale(saved);
    } else {
      const lang = navigator.language.toLowerCase();
      if (lang.startsWith('ko')) setLocale('ko');
      else if (lang.startsWith('ja')) setLocale('ja');
    }
  }, []);

  // HTML lang 속성을 현재 locale에 맞게 동기화
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale;
    }
  }, [locale]);

  // 로그인/이메일 인증 후 user_metadata.preferred_language → locale 동기화
  useEffect(() => {
    const supabase = createClient();
    const syncFromSession = (session: { user?: { user_metadata?: { preferred_language?: string } } } | null) => {
      // localStorage에 이미 언어가 있으면 user_metadata로 덮어쓰지 않음
      // (헤더에서 수동 변경한 언어를 세션 sync가 리셋하는 것을 방지)
      const saved = localStorage.getItem('vf6-locale');
      if (saved && ['ko', 'en', 'ja'].includes(saved)) return;

      const userLang = session?.user?.user_metadata?.preferred_language;
      if (userLang && ['ko', 'en', 'ja'].includes(userLang)) {
        setLocale(userLang as Locale);
        localStorage.setItem('vf6-locale', userLang);
      }
    };
    supabase.auth.getSession().then(({ data: { session } }) => syncFromSession(session));
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_IN' || event === 'INITIAL_SESSION') {
        syncFromSession(session);
      }
    });
    return () => subscription.unsubscribe();
  }, []);

  const handleSetLocale = (newLocale: Locale) => {
    setLocale(newLocale);
    localStorage.setItem('vf6-locale', newLocale);
  };

  const t = (key: string) => {
    const translation = (messages[locale] as any)[key];
    return translation !== undefined ? translation : key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const defaultContext: LanguageContextType = {
  locale: 'ko',
  setLocale: () => {},
  t: (key: string) => key,
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  // SSR/하이드레이션 시 Provider 미탑재 시 기본값 반환 (Next.js 16 인증 후 이동 시 오류 방지)
  return context ?? defaultContext;
}
